
# create client
../composable-ibc/target/release/hyperspace create-clients --config-a ./scripts/relayer_hyperspace/config-chain-a.toml --config-b ./scripts/relayer_hyperspace/config-chain-b.toml --config-core ./scripts/relayer_hyperspace/config.toml --delay-period 10

# # create connection
# ../composable-ibc/target/release/hyperspace create-connection --config-a ./scripts/relayer_hyperspace/config-chain-a.toml --config-b ./scripts/relayer_hyperspace/config-chain-b.toml --config-core ./scripts/relayer_hyperspace/config.toml --delay-period 1 --port-id transfer --order unordered

# # create channel
# ../composable-ibc/target/release/hyperspace create-channel --config-a ./scripts/relayer_hyperspace/config-chain-a.toml --config-b ./scripts/relayer_hyperspace/config-chain-b.toml --config-core ./scripts/relayer_hyperspace/config.toml --delay-period 0 --port-id tranfer --order unordered --version ics20-1

# # start relayer
# ../composable-ibc/target/release/hyperspace relay --config-a ./scripts/relayer_hyperspace/config-chain-a.toml --config-b ./scripts/relayer_hyperspace/config-chain-b.toml --config-core ./scripts/relayer_hyperspace/config.toml --delay-period 1 --port-id transfer --order unordered --version ics20-1

# # send ibc
# centaurid tx ibc-transfer transfer transfer channel-0 --chain-id test-1 5yNZjX24n2eg7W6EVamaTXNQbWCwchhThEaSWB7V3GRjtHeL 100stake